name: Post coverage comment

on:
  workflow_call:

jobs:
  test:
    name: "Display code coverage"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write # needed to edit the comment vs opening multiple ones
      actions: read
    steps:
      - name: "Post coverage comment 💬"
        uses: py-cov-action/python-coverage-comment-action@970a227e0c16ef4589a99a9970ab0ceb8c53059a
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.run_id }}
